name: Day 29 Production Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore
        working-directory: Azure-30-Day-Challenge/Day29-Production-Project/app/EmployeeApi

      - name: Build
        run: dotnet build --no-restore
        working-directory: Azure-30-Day-Challenge/Day29-Production-Project/app/EmployeeApi

      - name: Publish
        run: dotnet publish -c Release -o publish
        working-directory: Azure-30-Day-Challenge/Day29-Production-Project/app/EmployeeApi