name: Day 30 Capstone

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:

  build:
    name: Build .NET API
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore app/EmployeeApi/EmployeeApi.csproj

      - name: Build application
        run: dotnet build app/EmployeeApi/EmployeeApi.csproj --configuration Release --no-restore

  bicep:
    name: Validate Bicep
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Bicep
        run: az bicep install

      - name: Build Bicep
        run: az bicep build --file infra/Infra/main.bicep