name: Day 25 CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show repository
        run: ls -la

      - name: Build message
        run: echo "Build completed successfully"
